version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing dependencies...

  pre_build:
    commands:
      - echo Pre-build phase...

  build:
    commands:
      - echo Build started...
      - mvn clean install

  post_build:
    commands:
      - echo Build completed successfully.
      - echo Creating artifact directory...
      - mkdir -p artifact
      - cp target/*.jar artifact/

artifacts:
  files:
    - artifact/*.jar
    - appspec.yml
    - scripts/*
